import { randomUUID } from "node:crypto";
import { copyFile, mkdir, mkdtemp, readdir, rm, stat } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import path from "node:path";
import { runProcess, type RunResult } from "./process.js";

export type CliTool = "claude" | "codex";

export interface CliInvocation {
  tool: CliTool;
  args: string[];
  input: string;
  /** Host directory to consult read-only. Becomes the CLI's working directory. */
  referenceDir?: string;
  /** Host directory with the attachment images. Mounted read-only at /attachments in Docker. */
  attachmentsDir?: string;
  /** Host directory that receives outputs the CLI creates (codex generated images). Mounted at /out in Docker. */
  outputDir?: string;
  /** Called for each line of CLI stdout. (event stream) */
  onOutputLine?: (line: string) => void;
  timeoutMs: number;
  signal?: AbortSignal;
}

/** Where to run the CLI. Directly on the host or in a disposable Docker container. */
export interface Executor {
  readonly kind: "host" | "docker";
  /** Whether the given CLI can read files in the reference directory in this environment */
  canReadFiles(tool: CliTool): boolean;
  /** Maps an attachment's host path to the path the CLI sees. */
  attachmentPath(hostPath: string): string;
  /** Extracts text from a PDF. In Docker, runs in a disposable container without network access. */
  extractPdfText(pdfPath: string): Promise<string>;
  run(invocation: CliInvocation): Promise<RunResult>;
  /** Checks the prerequisites for running. Returns a list of problems. */
  verify(): Promise<string[]>;
}

/** First 50 pages only, in UTF-8, without warnings */
const PDFTOTEXT_ARGS = ["-l", "50", "-enc", "UTF-8", "-q"];

/**
 * docker run arguments for PDF text extraction. Since it parses files uploaded by other people, it runs
 * in a disposable container with no network, a read-only root, and all capabilities dropped.
 */
export function pdfExtractArgs(image: string, pdfPath: string): string[] {
  return [
    "run",
    "--rm",
    "--network",
    "none",
    "--read-only",
    "--cap-drop",
    "ALL",
    "--security-opt",
    "no-new-privileges",
    "--user",
    "1000:1000",
    "--memory",
    "512m",
    "--pids-limit",
    "64",
    "--label",
    SANDBOX_LABEL,
    "-v",
    `${path.dirname(pdfPath)}:/in:ro`,
    "--entrypoint",
    "pdftotext",
    image,
    ...PDFTOTEXT_ARGS,
    `/in/${path.basename(pdfPath)}`,
    "-",
  ];
}

/**
 * Images generated by codex running on the host are left in ~/.codex/generated_images.
 * Copies only the files created after the run started into outputDir.
 */
async function collectCodexImages(outputDir: string, sinceMs: number): Promise<void> {
  const root = path.join(
    process.env.CODEX_HOME ?? path.join(homedir(), ".codex"),
    "generated_images"
  );
  const sessions = await readdir(root).catch(() => [] as string[]);
  for (const session of sessions) {
    const dir = path.join(root, session);
    for (const name of await readdir(dir).catch(() => [] as string[])) {
      const file = path.join(dir, name);
      const info = await stat(file).catch(() => undefined);
      if (!info?.isFile() || info.mtimeMs < sinceMs) continue;
      await mkdir(outputDir, { recursive: true });
      await copyFile(file, path.join(outputDir, `${session}-${name}`));
    }
  }
}

export class HostExecutor implements Executor {
  readonly kind = "host" as const;

  constructor(private readonly bins: Record<CliTool, string>) {}

  canReadFiles(): boolean {
    return true;
  }

  attachmentPath(hostPath: string): string {
    return hostPath;
  }

  async extractPdfText(pdfPath: string): Promise<string> {
    const { stdout } = await runProcess("pdftotext", [...PDFTOTEXT_ARGS, pdfPath, "-"], {
      cwd: path.dirname(pdfPath),
      input: "",
      timeoutMs: 60_000,
    });
    return stdout;
  }

  async run(invocation: CliInvocation): Promise<RunResult> {
    const started = Date.now();
    try {
      return await this.runInDir(invocation);
    } finally {
      if (invocation.outputDir && invocation.tool === "codex") {
        await collectCodexImages(invocation.outputDir, started);
      }
    }
  }

  private async runInDir(invocation: CliInvocation): Promise<RunResult> {
    const run = (cwd: string) =>
      runProcess(this.bins[invocation.tool], invocation.args, {
        cwd,
        input: invocation.input,
        timeoutMs: invocation.timeoutMs,
        signal: invocation.signal,
        onStdoutLine: invocation.onOutputLine,
      });
    if (invocation.referenceDir) return run(invocation.referenceDir);
    // Without a reference directory, runs in an empty temporary directory.
    const scratch = await mkdtemp(path.join(tmpdir(), "orbly-"));
    try {
      return await run(scratch);
    } finally {
      await rm(scratch, { recursive: true, force: true });
    }
  }

  async verify(): Promise<string[]> {
    return [];
  }
}

export interface DockerSandboxOptions {
  dockerBin: string;
  image: string;
  network: string;
  proxyUrl: string;
  memory: string;
  cpus: string;
  /** Auth environment variables passed to the container for claude runs (CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY) */
  claudeEnv: Record<string, string>;
  /** Host auth.json mounted read-only for codex runs */
  codexAuthFile?: string;
  /** Hosts reached directly on the internal network without the proxy (e.g. ops-broker) */
  noProxy?: string[];
  /** Names of internal service containers that must be running at startup */
  requiredServices?: string[];
}

export const SANDBOX_LABEL = "verda.role=reasoner";
const CONTAINER_WORKSPACE = "/workspace";
const CONTAINER_EMPTY_DIR = "/work";
const CONTAINER_ATTACHMENTS = "/attachments";

/**
 * docker run arguments for the disposable reasoner container.
 * - Read-only root filesystem; HOME and /tmp are tmpfs, empty on every run
 * - All capabilities dropped, no privilege escalation, process/memory/CPU limits
 * - Connected only to the internal network. Outbound traffic goes only through the egress proxy (allowed domains).
 * - The only visible host files are the reference directory (read-only) and the codex auth file (read-only).
 * - Secrets are passed by name only (-e NAME), with values supplied through the docker CLI process environment. (keeps them out of ps)
 */
export function dockerRunArgs(
  options: DockerSandboxOptions,
  invocation: Pick<
    CliInvocation,
    "tool" | "args" | "referenceDir" | "attachmentsDir" | "outputDir"
  >,
  containerName: string
): string[] {
  const args = [
    "run",
    "--rm",
    "-i",
    "--name",
    containerName,
    "--label",
    SANDBOX_LABEL,
    "--network",
    options.network,
    "--read-only",
    "--tmpfs",
    "/tmp:rw,nosuid,nodev,size=256m",
    "--tmpfs",
    "/home/node:rw,nosuid,nodev,size=256m,uid=1000,gid=1000,mode=0700",
    "--cap-drop",
    "ALL",
    "--security-opt",
    "no-new-privileges",
    "--pids-limit",
    "256",
    "--memory",
    options.memory,
    "--cpus",
    options.cpus,
    "--user",
    "1000:1000",
    "-e",
    `HTTPS_PROXY=${options.proxyUrl}`,
    "-e",
    `HTTP_PROXY=${options.proxyUrl}`,
  ];
  if (options.noProxy?.length) {
    const list = options.noProxy.join(",");
    args.push("-e", `NO_PROXY=${list}`, "-e", `no_proxy=${list}`);
  }
  if (invocation.tool === "claude") {
    for (const name of Object.keys(options.claudeEnv)) args.push("-e", name);
  }
  if (invocation.tool === "codex" && options.codexAuthFile) {
    args.push("-v", `${options.codexAuthFile}:/run/secrets/codex-auth.json:ro`);
  }
  if (invocation.attachmentsDir) {
    args.push("-v", `${invocation.attachmentsDir}:${CONTAINER_ATTACHMENTS}:ro`);
  }
  // The container's only writable host path. The entrypoint links ~/.codex/generated_images here.
  if (invocation.outputDir && invocation.tool === "codex") {
    args.push("-v", `${invocation.outputDir}:/out`);
  }
  if (invocation.referenceDir) {
    args.push("-v", `${invocation.referenceDir}:${CONTAINER_WORKSPACE}:ro`);
    args.push("-w", CONTAINER_WORKSPACE);
  } else {
    args.push("-w", CONTAINER_EMPTY_DIR);
  }
  args.push(options.image, invocation.tool, ...invocation.args);
  return args;
}

export class DockerExecutor implements Executor {
  readonly kind = "docker" as const;

  constructor(private readonly options: DockerSandboxOptions) {}

  /**
   * codex reads files through the shell, but inside the hardened container its own sandbox (bubblewrap)
   * cannot create namespaces, so commands are rejected. Instead of loosening the outer isolation, file reading is turned off.
   */
  canReadFiles(tool: CliTool): boolean {
    return tool === "claude";
  }

  attachmentPath(hostPath: string): string {
    return `${CONTAINER_ATTACHMENTS}/${path.basename(hostPath)}`;
  }

  async extractPdfText(pdfPath: string): Promise<string> {
    const { stdout } = await runProcess(
      this.options.dockerBin,
      pdfExtractArgs(this.options.image, pdfPath),
      { cwd: process.cwd(), input: "", timeoutMs: 60_000 }
    );
    return stdout;
  }

  async run(invocation: CliInvocation): Promise<RunResult> {
    const name = `verda-reasoner-${randomUUID().slice(0, 8)}`;
    const env: NodeJS.ProcessEnv = { ...process.env };
    if (invocation.tool === "claude") Object.assign(env, this.options.claudeEnv);
    const referenceDir = this.canReadFiles(invocation.tool)
      ? invocation.referenceDir
      : undefined;
    try {
      return await runProcess(
        this.options.dockerBin,
        dockerRunArgs(this.options, { ...invocation, referenceDir }, name),
        {
          cwd: process.cwd(),
          input: invocation.input,
          timeoutMs: invocation.timeoutMs,
          signal: invocation.signal,
          env,
          onStdoutLine: invocation.onOutputLine,
        }
      );
    } catch (err) {
      // The container may be left behind if the docker CLI is killed, so it is removed.
      await runProcess(this.options.dockerBin, ["rm", "-f", name], {
        cwd: process.cwd(),
        input: "",
        timeoutMs: 15_000,
      }).catch(() => undefined);
      throw err;
    }
  }

  async verify(): Promise<string[]> {
    const { dockerBin, image, network } = this.options;
    const docker = (args: string[]) =>
      runProcess(dockerBin, args, { cwd: process.cwd(), input: "", timeoutMs: 15_000 });
    const problems: string[] = [];

    try {
      await docker(["version", "--format", "{{.Server.Version}}"]);
    } catch (err) {
      return [`Cannot connect to the docker daemon: ${(err as Error).message}`];
    }
    await docker(["image", "inspect", image]).catch(() =>
      problems.push(`Sandbox image ${image} not found. (pnpm sandbox:build)`)
    );
    try {
      const { stdout } = await docker([
        "network",
        "inspect",
        network,
        "--format",
        "{{.Internal}}",
      ]);
      if (stdout.trim() !== "true") {
        problems.push(
          `Network ${network} is not internal. Containers can reach the outside directly.`
        );
      }
    } catch {
      problems.push(`Sandbox network ${network} not found. (pnpm sandbox:up)`);
    }
    const { stdout: proxies } = await docker([
      "ps",
      "--filter",
      `network=${network}`,
      "--filter",
      "name=egress-proxy",
      "--format",
      "{{.Names}}",
    ]).catch(() => ({ stdout: "" }));
    if (!proxies.trim()) {
      problems.push("The egress proxy is not running. (pnpm sandbox:up)");
    }
    for (const service of this.options.requiredServices ?? []) {
      const { stdout } = await docker([
        "ps",
        "--filter",
        `network=${network}`,
        "--filter",
        `name=${service}`,
        "--format",
        "{{.Names}}",
      ]).catch(() => ({ stdout: "" }));
      if (!stdout.trim())
        problems.push(`${service} is not running. (pnpm sandbox:ops-up)`);
    }
    return problems;
  }
}
